[unstable]
build-std = ["core", "compiler_builtins", "alloc"] #+ `"alloc"`
build-std-features = ["compiler-builtins-mem"]


[build]
target = "x86_64-os_test.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"