name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : SetUp
      run : rustup override set nightly && rustup component add llvm-tools-preview && rustup component add rust-src
    - name: Build
      run: cargo build --verbose
# TODO : enable tests
#    - name: Run tests
#      run: cargo test --verbose
